set -s escape-time 0

# デフォルトシェルをfishに設定
set-option -g default-shell "/usr/bin/fish"

set -g set-clipboard on
bind g popup -xC -yC -w90% -h90% -E -d "#{pane_current_path}" "lazygit"
bind '"' split-window -v -c "#{pane_current_path}"
bind %  split-window -h -c "#{pane_current_path}"

# Active pane highlighting
# Reference: https://zenn.dev/kabec_dev/articles/410915fe7b5a1a

# 境界線のスタイル
set -g pane-border-lines single

# アクティブなペインの枠線: 青
set -g pane-active-border-style fg=blue

# 非アクティブなペインの枠線: 白
set -g pane-border-style fg=white

# ペインのラベル表示
set -g pane-border-status bottom
set -g pane-border-format "#{?pane_active,#[fg=white]#[bg=blue] Active #[fg=default]#[bg=default],} #P: #{pane_current_command}"

# 設定ファイルをリロードする
bind r source-file ~/.tmux.conf \; display "Reloaded!"

set -g allow-passthrough on

# コピーモードのキーバインドをviモードに設定
set-window-option -g mode-keys vi

# vで選択を開始する
bind-key -T copy-mode-vi v send-keys -X begin-selection

# <C-a>でペイン内の全履歴を全選択
bind-key -T copy-mode-vi C-a send-keys -X history-top \; send-keys -X begin-selection \; send-keys -X history-bottom

# <C-c>で選択範囲をコピーしてコピーモードを抜ける
if-shell -b '[ "$XDG_SESSION_TYPE" = "wayland" ]' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"'
if-shell -b '[ -n "$WSL_DISTRO_NAME" ]' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip.exe"'
